/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Class.*;
/**
 *
 * @author Meus documentos
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoApare = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCadastro = new javax.swing.JMenuItem();
        verificar = new javax.swing.JMenuItem();
        numCadastro = new javax.swing.JMenuItem();
        Sobre = new javax.swing.JMenu();
        verSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setResizable(false);

        javax.swing.GroupLayout CampoApareLayout = new javax.swing.GroupLayout(CampoApare);
        CampoApare.setLayout(CampoApareLayout);
        CampoApareLayout.setHorizontalGroup(
            CampoApareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        CampoApareLayout.setVerticalGroup(
            CampoApareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MenuItemCadastro.setText("Cadastrar");
        MenuItemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCadastro);

        verificar.setText("Verificar");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        jMenu1.add(verificar);

        numCadastro.setText("Número de cadastro");
        numCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(numCadastro);

        jMenuBar1.add(jMenu1);

        Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bullet_black.png"))); // NOI18N
        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });

        verSobre.setText("Ver sobre");
        verSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSobreActionPerformed(evt);
            }
        });
        Sobre.add(verSobre);

        jMenuBar1.add(Sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CampoApare)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CampoApare, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void MenuItemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastroActionPerformed
        // TODO add your handling code here:
        Cadastrar cadastro = new Cadastrar();
        CampoApare.add(cadastro);
        cadastro.setVisible(true);
        
    }//GEN-LAST:event_MenuItemCadastroActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SobreActionPerformed

    private void verSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSobreActionPerformed
        // TODO add your handling code here:
        Sobre sobre = new Sobre();
        CampoApare.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_verSobreActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        // TODO add your handling code here:
        Verificar veri = new Verificar();
        CampoApare.add(veri);
        veri.setVisible(true);
        
    }//GEN-LAST:event_verificarActionPerformed

    private void numCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCadastroActionPerformed
        // TODO add your handling code here:
        int num_cadastrados = Pessoa.num_pessoas;
        String mostrar = Integer.toString(num_cadastrados);
        JOptionPane.showMessageDialog(null, "Pessoas cadastradas: "+mostrar);
    }//GEN-LAST:event_numCadastroActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane CampoApare;
    private javax.swing.JMenuItem MenuItemCadastro;
    private javax.swing.JMenu Sobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem numCadastro;
    private javax.swing.JMenuItem verSobre;
    private javax.swing.JMenuItem verificar;
    // End of variables declaration//GEN-END:variables
}
